project:
  type: website
execute:
  echo: true
  keep-ipynb: true

website:
  title: "Advanced Macro: Numerical Methods"
  sidebar:
      style: "docked"
      search: true
      contents:
        - section: "Slides"
          contents:
            - slides/session_1/index.qmd
            - slides/session_2/index.qmd
            - slides/session_3/index.qmd
            - slides/session_4/index.qmd
            - slides/ddp.qmd
            - slides/discretization.qmd
            - slides/interpolation.qmd
            - slides/time_iteration.qmd

        - section: "Tutorials"
          contents:
            - tutorials/1_Julia_Basics.ipynb
            - tutorials/2_solow.ipynb
            - tutorials/3_perturbation_neoclassical.ipynb
            - tutorials/4_Optimization.ipynb
            - tutorials/6_discrete_dynamic_programming.ipynb
            - tutorials/6_discrete_dynamic_programming_mccall_correction.ipynb
        
        - section: "Pushups"
          contents:
            - pushups/1_epidemiology.ipynb
            - pushups/2_Optimization_pushups.ipynb
            - pushups/Exam_mie37_2023.ipynb

        - section: "Graded"
          contents:
            - homework/2024/Coursework_mie37_2024.ipynb
  
format:
  html:
    theme: flatly
    css: styles.css
    toc: true



