project:
  type: website
execute:
  echo: true

website:
  title: "Advanced Macro: Numerical Methods"
  sidebar:
      style: "docked"
      search: true
      contents:
        - section: "Slides"
          contents:
            - slides/session_1/index.qmd
            - slides/session_2/index.qmd
            - slides/session_3/index.qmd
            - slides/session_4/index.qmd
            - slides/session_ddp/index.qmd
            - slides/discretization.qmd
            - slides/interpolation.qmd
            - slides/time_iteration.qmd

        - section: "Tutorials"
          contents:
            - tutorials/1_Julia_Basics.ipynb
            - tutorials/1_epidemiology.ipynb
            - tutorials/2_solow.ipynb
            - tutorials/3_perturbation_neoclassical.ipynb
            - tutorials/4_Optimization.ipynb
            - tutorials/6_discrete_dynamic_programming.ipynb
            - tutorials/mccall.ipynb
            # - tutorials/6_discrete_dynamic_programming_mccall_correction.ipynb
        
        - section: "Pushups"
          contents:
            - pushups/2_Optimization_pushups.ipynb
        
        - section: Exams
          contents:
            - exam/2023/Exam_mie37_2023.ipynb
            - exam/2024/Exam_mie37_2024.ipynb
            - exam/2025/Exam_mie37_2025.qmd

        - section: "Coursework"
          contents:
            - homework/2025/coursework_1.ipynb
            - homework/2025/coursework_2.ipynb
            - homework/2025/coursework_3.qmd
  
format:
  html:
    theme: flatly
    css: styles.css
    toc: true



