project:
  type: website
execute:
  echo: true
  keep-ipynb: true

website:
  title: "Advanced Macro: Numerical Methods"
  sidebar:
      style: "docked"
      search: true
      contents:
        - section: "Slides"
          contents:
            - slides/session_1/index.qmd
            - slides/session_2/index.qmd
            - slides/perturbation.qmd
            - slides/ddp.qmd
            - slides/discretization.qmd
            - slides/optimization.qmd
            - slides/interpolation.qmd
            - slides/time_iteration.qmd

        - section: "Tutorials"
          contents:
            - tutorials/1_Julia_Basics.ipynb
            - tutorials/2_solow.ipynb
            # - notebooks/2_solow_correction.ipynb
            # - notebooks/3_perturbation_neoclassical_correction.ipynb
            # - notebooks/7_Optimization_correction.ipynb
            # - notebooks/8_smooth_vfi.ipynb
        
        - section: "Pushups"
          contents:
            - pushups/1_epidemiology.ipynb
  
format:
  html:
    theme: flatly
    css: styles.css
    toc: true



