---
title: "Advanced Macro: Numerical Methods"
listing:
  id: course-listing
  type: table
  sort-ui: false
  filter-ui: false
  contents:
    - slides/session_*/index.qmd
    - prep*/index.qmd
    - slides/ddp.qmd
    - slides/discretization.qmd
    - slides/interpolation.qmd
    - slides/time_iteration.qmd

  sort: date
  fields: [date, title]
---

<mark>EXAM</mark>

- checkout the exam [Notebook](exam/2024/Exam_mie37_2024.ipynb)
  - use the download link on the right part of the page ("Other Format / Jupyter")
- complete the notebook
- send by email by 11:30
- have fun!

<mark>TODO</mark>

- work on the [Coursework](homework/2024/Coursework_mie37_2024.ipynb)
  - due for May 24th


## Indicative Schedule

::: {#course-listing}

:::

## Communication

- Zulip (best)
- Email to `pwinant@escp.eu` starting with `[mie37]`
- Github issues (PR also welcome)

## Assessments

- tutorials (optional) + projects (mandatory) (50%)
- final exam (50%)




::: {.callout-caution collapse="true" title="Last Year's Schedule"}

### Indicative Schedule

| Date               | Content                                                                                                             | Homework               |
| ------------------ | ------------------------------------------------------------------------------------------------------------------- | ---------------------- |
| 02/02              | [Intro](slides/session_1/introduction.qmd), Julia Basics (1)                                           | Epidemiology Tutorial  |
| 09/02              | [Convergence of Sequences](http://www.mosphere.fr/mie37/slides/convergence.html), Julia Basics (2),  Solow Tutorial | Finish Solow Tutorial  |
| 16/02              | [Perturbation](http://www.mosphere.fr/mie37/slides/perturbation.html) (1)                                                                                                    | Finish Neoclassical    |
| 23/02              | Perturbation (2)                                                                                                    |                        |
| 8/03               | Discrete Dynamic Programming, McCall Model       |                        |
| 16/03              | Discrete Dynamic Programming, McCall Model                     |                        |
| 23/03              | McCall Model (2)                                                                                                    |                        |
| 30/03              | Discretization                                                                                         |    Coursework                    |
| <mark>06/04</mark>              | Interpolation                                                                                      |          |
| 13/04              | Approximate Dynamic Programming (VFI)                                                                                      |          |

:::